/* ==========================================================================
   Leyes de la Vida — Catálogo de leyes
   Autor: Jeshua Romero Guadarrama
   Cada entrada: id, nombre, autor, anio, cat, enunciado, explicacion,
   ejemplo, tags, rel (leyes relacionadas), sim (interactivo asociado).
   ========================================================================== */

window.CATEGORIAS = {
  eco: { nombre: "Economía", color: "var(--eco)", icono: "📈", desc: "Mercados, dinero, incentivos y decisiones de consumo." },
  psi: { nombre: "Psicología", color: "var(--psi)", icono: "🧠", desc: "Percepción, memoria, aprendizaje y conducta humana." },
  soc: { nombre: "Sociología y comunicación", color: "var(--soc)", icono: "🗣️", desc: "Grupos, instituciones, debate público e internet." },
  ges: { nombre: "Gestión y organizaciones", color: "var(--ges)", icono: "🏢", desc: "Trabajo, burocracia, proyectos y planificación." },
  tec: { nombre: "Tecnología y sistemas", color: "var(--tec)", icono: "💻", desc: "Software, redes, cómputo y sistemas complejos." },
  est: { nombre: "Estadística y datos", color: "var(--est)", icono: "🎲", desc: "Probabilidad, distribuciones y trampas de los datos." },
  med: { nombre: "Medicina y fisiología", color: "var(--med)", icono: "🩺", desc: "Clínica, psiquiatría, fisiología y salud pública." }
};

window.LEYES = [
  /* ======================= ECONOMÍA ======================= */
  {
    id: "gresham",
    nombre: "Ley de Gresham",
    autor: "Thomas Gresham",
    anio: "siglo XVI",
    cat: "eco",
    enunciado: "El dinero malo expulsa de la circulación al dinero bueno.",
    explicacion: "Cuando circulan dos monedas con el mismo valor legal pero distinto valor intrínseco, la gente paga con la de peor calidad y atesora, funde o exporta la mejor. El resultado es que en la calle solo queda el dinero devaluado. El principio se generaliza: cuando lo bueno y lo malo se aceptan al mismo precio, lo malo tiende a dominar.",
    ejemplo: "Al degradarse la plata de las monedas, las piezas antiguas con más metal precioso desaparecían de la circulación: todo el mundo pagaba con las nuevas y guardaba las viejas. Hoy se aplica a mercados donde productos mediocres desplazan a los de calidad si el comprador no puede distinguirlos.",
    tags: ["dinero", "moneda", "circulación", "atesorar", "valor"],
    rel: ["goodhart", "sturgeon"],
    sim: "sim-gresham"
  },
  {
    id: "goodhart",
    nombre: "Ley de Goodhart",
    autor: "Charles Goodhart",
    anio: "1975",
    cat: "eco",
    enunciado: "Cuando una medida se convierte en objetivo, deja de ser una buena medida.",
    explicacion: "Un indicador estadístico funciona mientras nadie tiene incentivos para manipularlo. En cuanto se usa para premiar o castigar, la gente optimiza el número y no la realidad que el número intentaba reflejar. La correlación que hacía útil al indicador se destruye por el propio hecho de usarlo como meta.",
    ejemplo: "Si se paga a un centro de llamadas por 'llamadas atendidas por hora', los operadores acortarán las llamadas sin resolver los problemas: la métrica sube y el servicio real empeora.",
    tags: ["métricas", "indicadores", "incentivos", "objetivos", "KPI"],
    rel: ["campbell", "gresham", "twyman"],
    sim: "sim-goodhart"
  },
  {
    id: "say",
    nombre: "Ley de Say",
    autor: "Jean-Baptiste Say",
    anio: "1803",
    cat: "eco",
    enunciado: "Toda oferta crea su propia demanda.",
    explicacion: "Producir bienes genera al mismo tiempo los ingresos (salarios, beneficios, rentas) con los que se compran otros bienes, de modo que la producción agregada no puede exceder de forma permanente a la demanda agregada. Keynes la discutió intensamente: en crisis, la gente puede atesorar en lugar de gastar, y la demanda sí puede quedarse corta.",
    ejemplo: "Un panadero que produce pan obtiene ingresos con los que compra zapatos y ropa; su oferta de pan se convierte en demanda de otros productos. La Gran Depresión mostró los límites de este razonamiento.",
    tags: ["oferta", "demanda", "producción", "clásicos", "Keynes"],
    rel: ["oferta-demanda", "okun"]
  },
  {
    id: "engel",
    nombre: "Ley de Engel",
    autor: "Ernst Engel",
    anio: "1857",
    cat: "eco",
    enunciado: "A medida que aumenta el ingreso de una familia, disminuye la proporción que gasta en alimentos.",
    explicacion: "Aunque el gasto absoluto en comida crece con el ingreso, su peso relativo en el presupuesto cae, porque la capacidad del estómago tiene límites y el dinero extra se destina a vivienda, educación, ocio o ahorro. El porcentaje de gasto en alimentación se usa como indicador del nivel de vida de un país.",
    ejemplo: "Un hogar con ingresos bajos puede dedicar la mitad de su presupuesto a comer; un hogar acomodado, apenas una décima parte, aunque compre productos más caros.",
    tags: ["consumo", "ingreso", "alimentos", "presupuesto", "pobreza"],
    rel: ["gossen", "wagner"]
  },
  {
    id: "okun",
    nombre: "Ley de Okun",
    autor: "Arthur Okun",
    anio: "1962",
    cat: "eco",
    enunciado: "Por cada punto que el desempleo sube por encima de su tasa natural, el PIB cae aproximadamente dos puntos respecto a su potencial.",
    explicacion: "Es una regularidad empírica, no una ley exacta: relaciona el crecimiento económico con el empleo. Para reducir el paro no basta con crecer, hay que crecer por encima de la tendencia, porque la productividad y la población activa también aumentan.",
    ejemplo: "Una economía que crece al 1% cuando su tendencia es el 3% suele ver subir el desempleo, aunque técnicamente no esté en recesión.",
    tags: ["desempleo", "PIB", "crecimiento", "macroeconomía", "paro"],
    rel: ["say", "wagner"]
  },
  {
    id: "pareto",
    nombre: "Principio de Pareto (regla 80/20)",
    autor: "Vilfredo Pareto",
    anio: "1896",
    cat: "eco",
    enunciado: "Aproximadamente el 80% de los efectos proviene del 20% de las causas.",
    explicacion: "Pareto observó que el 80% de la tierra en Italia pertenecía al 20% de la población. La misma asimetría aparece en ventas, defectos de software, uso de funciones y casi cualquier fenómeno con distribución muy desigual. No es una ley exacta sino un patrón: pocas causas vitales, muchas triviales.",
    ejemplo: "En muchas empresas, una quinta parte de los clientes genera la mayor parte de la facturación; corregir el 20% de los errores más frecuentes de un programa elimina el 80% de los fallos reportados.",
    tags: ["80/20", "desigualdad", "concentración", "prioridades", "productividad"],
    rel: ["price", "zipf", "sturgeon"],
    sim: "sim-pareto"
  },
  {
    id: "rendimientos-decrecientes",
    nombre: "Ley de rendimientos decrecientes",
    autor: "Anne Robert Turgot; David Ricardo",
    anio: "siglo XVIII",
    cat: "eco",
    enunciado: "Si se añade más y más de un factor de producción manteniendo fijos los demás, el aumento de producción por unidad añadida acaba disminuyendo.",
    explicacion: "Los primeros trabajadores o fertilizantes en un campo rinden mucho; los siguientes, cada vez menos, porque el factor fijo (la tierra, la maquinaria) se satura. Es la razón de que 'más' no siempre sea 'proporcionalmente mejor' y fundamenta la forma de las curvas de costes.",
    ejemplo: "El primer café de la mañana despeja; el quinto apenas hace efecto y el décimo sienta mal. En una cocina pequeña, el tercer cocinero ayuda menos que el segundo, y el octavo estorba.",
    tags: ["producción", "marginal", "factores", "saturación"],
    rel: ["gossen", "brooks"]
  },
  {
    id: "oferta-demanda",
    nombre: "Ley de la oferta y la demanda",
    autor: "Alfred Marshall (formalización)",
    anio: "1890",
    cat: "eco",
    enunciado: "El precio de un bien tiende al punto donde la cantidad ofrecida iguala la cantidad demandada.",
    explicacion: "Si el precio está alto, sobra producto y los vendedores bajan precios; si está bajo, hay escasez y los compradores pujan al alza. El mercado busca el equilibrio como un termostato. Las 'leyes' componentes: a mayor precio, menos demanda y más oferta, salvo excepciones (bienes de Giffen o de lujo).",
    ejemplo: "Cuando una helada arruina la cosecha de aguacate, la oferta cae y el precio sube hasta que suficientes consumidores desisten de comprar.",
    tags: ["precio", "equilibrio", "mercado", "escasez"],
    rel: ["say", "hotelling"]
  },
  {
    id: "wagner",
    nombre: "Ley de Wagner",
    autor: "Adolph Wagner",
    anio: "1883",
    cat: "eco",
    enunciado: "El gasto público crece más deprisa que la economía a medida que los países se desarrollan.",
    explicacion: "Con el desarrollo aumenta la demanda de educación, sanidad, pensiones, infraestructura y regulación, de modo que el Estado absorbe una fracción creciente del PIB. Explica por qué los países ricos suelen tener sectores públicos proporcionalmente mayores que los pobres.",
    ejemplo: "En 1900 el gasto público de la mayoría de países europeos rondaba el 10% del PIB; hoy suele superar el 40%.",
    tags: ["gasto público", "Estado", "desarrollo", "impuestos"],
    rel: ["okun", "parkinson", "baumol"]
  },
  {
    id: "baumol",
    nombre: "Efecto Baumol (enfermedad de los costes)",
    autor: "William Baumol",
    anio: "1966",
    cat: "eco",
    enunciado: "Los salarios suben incluso en sectores donde la productividad no mejora, encareciendo sus servicios.",
    explicacion: "Un cuarteto de cuerda necesita hoy los mismos cuatro músicos y los mismos minutos que en 1800, pero sus salarios deben competir con los de sectores que sí se volvieron más productivos. Por eso educación, sanidad, cultura y cuidados se encarecen sistemáticamente respecto a los bienes manufacturados.",
    ejemplo: "Los televisores bajan de precio década tras década mientras las matrículas universitarias y los conciertos suben: no por ineficiencia, sino porque enseñar y tocar siguen requiriendo el mismo tiempo humano.",
    tags: ["costes", "productividad", "servicios", "salarios", "sanidad"],
    rel: ["wagner", "moore"]
  },
  {
    id: "hierro-salarios",
    nombre: "Ley de hierro de los salarios",
    autor: "Ferdinand Lassalle",
    anio: "1863",
    cat: "eco",
    enunciado: "Los salarios tienden a largo plazo al mínimo necesario para la subsistencia del trabajador.",
    explicacion: "Basada en Ricardo y Malthus: si los salarios suben, la población obrera crece y la competencia por el empleo los vuelve a bajar. La historia la refutó —los salarios reales crecieron enormemente con la productividad—, pero es clave para entender el pensamiento económico del siglo XIX y el nacimiento del movimiento obrero.",
    ejemplo: "Sirvió de argumento a Lassalle para defender que los sindicatos por sí solos no podían mejorar los salarios y que hacía falta acción política.",
    tags: ["salarios", "subsistencia", "Malthus", "historia económica"],
    rel: ["rendimientos-decrecientes", "michels"]
  },
  {
    id: "gossen",
    nombre: "Primera ley de Gossen (utilidad marginal decreciente)",
    autor: "Hermann Heinrich Gossen",
    anio: "1854",
    cat: "eco",
    enunciado: "Cada unidad adicional consumida de un bien proporciona menos satisfacción que la anterior.",
    explicacion: "El primer vaso de agua para un sediento vale muchísimo; el quinto, casi nada. Esta idea resolvió la paradoja del valor (por qué el agua, vital, es barata, y el diamante, inútil, caro) y es el cimiento de la teoría moderna del consumidor.",
    ejemplo: "El primer episodio de una serie encanta; en el décimo seguido, la satisfacción por episodio ha caído tanto que apagas la televisión.",
    tags: ["utilidad", "marginal", "consumo", "satisfacción"],
    rel: ["rendimientos-decrecientes", "engel", "weber-fechner"]
  },
  {
    id: "jevons",
    nombre: "Paradoja de Jevons",
    autor: "William Stanley Jevons",
    anio: "1865",
    cat: "eco",
    enunciado: "Mejorar la eficiencia con que se usa un recurso puede aumentar, no reducir, su consumo total.",
    explicacion: "Al abaratarse el uso del recurso, se multiplican sus aplicaciones y usuarios, y el efecto rebote supera al ahorro. Jevons lo observó con el carbón: máquinas de vapor más eficientes dispararon el consumo total de carbón en Inglaterra.",
    ejemplo: "Motores más eficientes no vaciaron las carreteras: la gasolina rinde más, conducir sale más barato y se conduce más. Las bombillas LED consumen menos, así que iluminamos más superficies que nunca.",
    tags: ["eficiencia", "rebote", "energía", "recursos", "consumo"],
    rel: ["wirth", "parkinson"]
  },
  {
    id: "hotelling",
    nombre: "Ley de Hotelling",
    autor: "Harold Hotelling",
    anio: "1929",
    cat: "eco",
    enunciado: "Los competidores tienden a parecerse y situarse juntos en el centro del mercado.",
    explicacion: "Dos heladeros en una playa terminan espalda con espalda en el punto medio: cualquier otro sitio regala clientes al rival. Aplica al espacio físico y al 'espacio de ideas': productos, cadenas de televisión y partidos políticos convergen hacia el votante o consumidor mediano.",
    ejemplo: "Las gasolineras y farmacias agrupadas en la misma esquina, o dos grandes partidos cuyos programas se vuelven casi indistinguibles en época electoral.",
    tags: ["competencia", "localización", "diferenciación", "política"],
    rel: ["duverger", "oferta-demanda"]
  },

  /* ======================= TECNOLOGÍA Y SISTEMAS ======================= */
  {
    id: "moore",
    nombre: "Ley de Moore",
    autor: "Gordon Moore",
    anio: "1965",
    cat: "tec",
    enunciado: "El número de transistores en un chip se duplica aproximadamente cada dos años.",
    explicacion: "Más que una ley física es una profecía autocumplida que marcó el ritmo de la industria de semiconductores durante medio siglo: cada generación de chips dobla la densidad a coste similar. Su desaceleración actual (límites atómicos, calor, coste de fábricas) redefine la computación hacia chips especializados.",
    ejemplo: "El procesador de un teléfono actual contiene miles de millones de transistores; el Intel 4004 de 1971 tenía 2300. Esa curva exponencial es la razón de que un móvil supere a los superordenadores de los años 90.",
    tags: ["transistores", "chips", "exponencial", "semiconductores", "cómputo"],
    rel: ["wirth", "kryder", "metcalfe", "wright"]
  },
  {
    id: "metcalfe",
    nombre: "Ley de Metcalfe",
    autor: "Robert Metcalfe",
    anio: "1980",
    cat: "tec",
    enunciado: "El valor de una red crece con el cuadrado del número de usuarios conectados.",
    explicacion: "Con n usuarios hay n(n−1)/2 conexiones posibles: duplicar los usuarios cuadruplica las interacciones potenciales. Explica los efectos de red, el 'el ganador se lo lleva todo' de las plataformas y por qué una red social vacía no vale nada y una llena es casi imposible de abandonar.",
    ejemplo: "Un teléfono aislado es inútil; dos permiten una conversación; mil millones crean un mercado de comunicaciones. Por eso las mensajerías nuevas luchan tanto por arrancar aunque sean técnicamente mejores.",
    tags: ["redes", "efecto de red", "usuarios", "plataformas", "valor"],
    rel: ["brooks", "moore", "dunbar"]
  },
  {
    id: "wright",
    nombre: "Ley de Wright (curva de aprendizaje)",
    autor: "Theodore Wright",
    anio: "1936",
    cat: "tec",
    enunciado: "Cada vez que se duplica la producción acumulada de un producto, su coste unitario cae un porcentaje constante.",
    explicacion: "Estudiando la fabricación de aviones, Wright observó que la experiencia acumulada abarata la producción de forma predecible (típicamente 10–25% por duplicación). Predice mejor que la ley de Moore el abaratamiento de paneles solares, baterías y manufactura en general.",
    ejemplo: "El precio de los paneles solares ha caído en torno al 20% cada vez que la capacidad instalada mundial se ha duplicado, siguiendo esta curva durante décadas.",
    tags: ["aprendizaje", "costes", "manufactura", "experiencia", "escala"],
    rel: ["moore", "practica"]
  },
  {
    id: "wirth",
    nombre: "Ley de Wirth",
    autor: "Niklaus Wirth",
    anio: "1995",
    cat: "tec",
    enunciado: "El software se vuelve lento más deprisa de lo que el hardware se vuelve rápido.",
    explicacion: "Cada mejora de hardware se absorbe con capas de abstracción, funciones accesorias y desarrollo apresurado, de modo que la experiencia del usuario apenas mejora. También se enuncia como 'lo que Intel te da, Microsoft te lo quita'. Es la paradoja de Jevons aplicada a los ciclos de CPU.",
    ejemplo: "Un procesador de textos de hoy tarda en abrir lo mismo que uno de hace veinticinco años, pese a que el ordenador es miles de veces más potente.",
    tags: ["software", "rendimiento", "bloat", "hardware"],
    rel: ["moore", "jevons", "gall"]
  },
  {
    id: "kryder",
    nombre: "Ley de Kryder",
    autor: "Mark Kryder",
    anio: "2005",
    cat: "tec",
    enunciado: "La densidad de almacenamiento en disco se duplica aproximadamente cada año o año y medio.",
    explicacion: "Es el equivalente de la ley de Moore para el almacenamiento magnético: la capacidad por pulgada cuadrada creció incluso más rápido que la densidad de transistores durante décadas, abaratando el guardar 'todo para siempre'. Como Moore, se ha frenado en los últimos años.",
    ejemplo: "Un disco doméstico pasó de gigabytes a terabytes por el mismo precio en quince años, haciendo viable la fotografía sin borrar nada y los centros de datos en la nube.",
    tags: ["almacenamiento", "discos", "densidad", "datos"],
    rel: ["moore", "wright"]
  },
  {
    id: "conway",
    nombre: "Ley de Conway",
    autor: "Melvin Conway",
    anio: "1967",
    cat: "tec",
    enunciado: "Las organizaciones diseñan sistemas que copian su propia estructura de comunicación.",
    explicacion: "Si cuatro equipos construyen un compilador, saldrá un compilador de cuatro pasadas. Las fronteras entre módulos de software reflejan las fronteras entre departamentos, porque las interfaces técnicas se negocian por los mismos canales que las humanas. Se usa a la inversa ('maniobra de Conway inversa'): reorganiza los equipos según la arquitectura que deseas.",
    ejemplo: "Una web cuya sección de pagos parece de otra empresa delata que el equipo de pagos apenas hablaba con el resto.",
    tags: ["organizaciones", "arquitectura", "software", "equipos", "comunicación"],
    rel: ["brooks", "parkinson", "gall"]
  },
  {
    id: "brooks",
    nombre: "Ley de Brooks",
    autor: "Fred Brooks",
    anio: "1975",
    cat: "tec",
    enunciado: "Añadir personas a un proyecto de software retrasado lo retrasa todavía más.",
    explicacion: "Los recién llegados necesitan formación de quienes ya trabajan, y cada persona nueva multiplica los canales de comunicación (n(n−1)/2). El trabajo intelectual no es perfectamente divisible: 'nueve mujeres no gestan un bebé en un mes'. De 'The Mythical Man-Month', el libro clásico sobre gestión de software.",
    ejemplo: "Un equipo de 4 con fecha comprometida recibe 6 refuerzos; durante semanas la velocidad cae, porque los veteranos dejan de programar para explicar el sistema y coordinar a 10 personas en vez de a 4.",
    tags: ["proyectos", "plazos", "equipos", "software", "comunicación"],
    rel: ["conway", "hofstadter", "parkinson", "metcalfe"],
    sim: "sim-brooks"
  },
  {
    id: "linus",
    nombre: "Ley de Linus",
    autor: "Eric S. Raymond",
    anio: "1999",
    cat: "tec",
    enunciado: "Con suficientes ojos, todos los errores son evidentes.",
    explicacion: "Formulada en honor a Linus Torvalds: si hay bastantes revisores y probadores, casi cualquier fallo se detecta y corrige rápido. Es el argumento central a favor del software de código abierto, aunque con matices: los ojos deben mirar de verdad (fallos graves han sobrevivido años en código abierto muy usado).",
    ejemplo: "Un error en el núcleo Linux suele diagnosticarse en horas porque miles de desarrolladores pueden leer el código; el mismo fallo en un sistema cerrado depende de un único equipo.",
    tags: ["código abierto", "revisión", "errores", "colaboración"],
    rel: ["cunningham", "sturgeon"]
  },
  {
    id: "postel",
    nombre: "Ley de Postel (principio de robustez)",
    autor: "Jon Postel",
    anio: "1980",
    cat: "tec",
    enunciado: "Sé conservador en lo que envías y liberal en lo que aceptas.",
    explicacion: "Escrita en la especificación de TCP: un programa debe emitir datos estrictamente correctos pero tolerar entradas imperfectas de otros. Hizo posible que Internet funcionara entre implementaciones dispares, aunque hoy se debate: tolerar errores ajenos los perpetúa y crea problemas de seguridad.",
    ejemplo: "Los navegadores muestran páginas con HTML mal escrito en vez de fallar; gracias a eso la web creció, y por eso mismo el HTML descuidado se volvió la norma.",
    tags: ["protocolos", "Internet", "robustez", "interoperabilidad"],
    rel: ["gall", "conway"]
  },
  {
    id: "gall",
    nombre: "Ley de Gall",
    autor: "John Gall",
    anio: "1975",
    cat: "tec",
    enunciado: "Todo sistema complejo que funciona evolucionó de un sistema simple que funcionaba.",
    explicacion: "Un sistema complejo diseñado desde cero nunca funciona y no se puede parchear hasta que funcione: hay que empezar de nuevo desde algo simple. Es el fundamento del desarrollo iterativo, los productos mínimos viables y la desconfianza hacia los grandes rediseños 'big bang'.",
    ejemplo: "Internet evolucionó desde una red mínima entre cuatro universidades; los megaproyectos informáticos estatales diseñados completos sobre papel fracasan con regularidad.",
    tags: ["complejidad", "diseño", "iteración", "MVP", "sistemas"],
    rel: ["wirth", "conway", "clarke"]
  },
  {
    id: "clarke",
    nombre: "Tercera ley de Clarke",
    autor: "Arthur C. Clarke",
    anio: "1962",
    cat: "tec",
    enunciado: "Toda tecnología suficientemente avanzada es indistinguible de la magia.",
    explicacion: "La más citada de las tres leyes de Clarke sobre el futuro. Cuando el mecanismo de una tecnología escapa por completo a nuestra comprensión, la tratamos como magia: con asombro, fe o miedo, pero sin criterio. Advierte sobre cómo evaluamos (o dejamos de evaluar) lo que no entendemos.",
    ejemplo: "Para la mayoría, hablar con un asistente de voz o hacer una videollamada intercontinental es funcionalmente magia: nadie podría explicar la cadena completa que lo hace posible.",
    tags: ["tecnología", "futuro", "magia", "ciencia ficción"],
    rel: ["amara", "gall"]
  },
  {
    id: "amara",
    nombre: "Ley de Amara",
    autor: "Roy Amara",
    anio: "c. 1970",
    cat: "tec",
    enunciado: "Sobreestimamos el efecto de una tecnología a corto plazo y lo subestimamos a largo plazo.",
    explicacion: "Las tecnologías nuevas provocan primero una ola de expectativas infladas y decepción ('todavía no sirve'), y después, cuando ya nadie mira, transforman todo silenciosamente. Es el patrón del ciclo de sobreexpectación: pico de expectativas, valle de desilusión, meseta de productividad.",
    ejemplo: "Internet en 1999: burbuja y colapso porque 'prometía demasiado'; veinte años después reorganizó el comercio, el trabajo, la prensa y la vida social más de lo que nadie predijo.",
    tags: ["predicción", "expectativas", "adopción", "futuro"],
    rel: ["clarke", "dunning-kruger"]
  },
  {
    id: "amdahl",
    nombre: "Ley de Amdahl",
    autor: "Gene Amdahl",
    anio: "1967",
    cat: "tec",
    enunciado: "La mejora total de un sistema está limitada por la fracción que no se puede mejorar.",
    explicacion: "Si solo el 90% de una tarea es paralelizable, ni con infinitos procesadores irás más de 10 veces más rápido: el 10% secuencial pone el techo. Generaliza a cualquier optimización: acelerar una parte solo ayuda en proporción al peso de esa parte en el total.",
    ejemplo: "De nada sirve un coche que vuele en autopista si el trayecto incluye 20 minutos de atasco urbano: ese tramo fija el mínimo del viaje. En software, optimizar una función que ocupa el 2% del tiempo de ejecución es esfuerzo perdido.",
    tags: ["paralelismo", "optimización", "límites", "rendimiento"],
    rel: ["brooks", "pareto"]
  },

  /* ======================= PSICOLOGÍA ======================= */
  {
    id: "yerkes-dodson",
    nombre: "Ley de Yerkes-Dodson",
    autor: "Robert Yerkes y John Dodson",
    anio: "1908",
    cat: "psi",
    enunciado: "El rendimiento mejora con la activación hasta un punto óptimo; más allá, el exceso de estrés lo deteriora.",
    explicacion: "La relación entre activación (arousal) y rendimiento tiene forma de U invertida: sin tensión no hay energía; con demasiada, la ansiedad bloquea. El punto óptimo depende de la tarea: las tareas simples toleran (y agradecen) mucha activación; las complejas exigen calma.",
    ejemplo: "Unos nervios moderados antes de un examen ayudan a concentrarse; el pánico deja la mente en blanco. Un levantador de pesas rinde mejor 'encendido'; un cirujano, sereno.",
    tags: ["estrés", "ansiedad", "rendimiento", "activación", "examen"],
    rel: ["ebbinghaus", "efecto-thorndike"],
    sim: "sim-yerkes"
  },
  {
    id: "weber-fechner",
    nombre: "Ley de Weber-Fechner",
    autor: "Ernst Weber y Gustav Fechner",
    anio: "1834 / 1860",
    cat: "psi",
    enunciado: "La sensación percibida crece con el logaritmo del estímulo: notamos cambios relativos, no absolutos.",
    explicacion: "Para percibir una diferencia, el cambio debe ser una proporción constante del estímulo original (fracción de Weber). Por eso una vela ilumina una habitación oscura y es invisible a mediodía. Fundó la psicofísica y explica desde las escalas de decibelios hasta por qué duele igual pagar 5€ más en un café que 5€ más en un coche... espera: no duele igual, y esa es exactamente la ley.",
    ejemplo: "Distingues una mochila de 1 kg de una de 2 kg, pero no una de 30 kg de una de 31 kg: el mismo kilo añadido es proporcionalmente insignificante.",
    tags: ["percepción", "psicofísica", "estímulo", "logaritmo", "sensación"],
    rel: ["gossen", "hick", "fitts"],
    sim: "sim-weber"
  },
  {
    id: "hick",
    nombre: "Ley de Hick",
    autor: "William Hick y Ray Hyman",
    anio: "1952",
    cat: "psi",
    enunciado: "El tiempo para decidir crece logarítmicamente con el número de opciones disponibles.",
    explicacion: "Elegir entre 8 opciones no cuesta cuatro veces más que entre 2, sino según log₂(n+1): la mente descarta por bloques, como una búsqueda binaria. Es un pilar del diseño de interfaces y menús: cada opción añadida tiene un coste cognitivo, aunque decreciente.",
    ejemplo: "Un mando a distancia con 50 botones paraliza; los menús de los restaurantes interminables alargan el pedido. Por eso las interfaces bien diseñadas agrupan y jerarquizan opciones.",
    tags: ["decisión", "opciones", "menús", "interfaces", "UX", "tiempo de reacción"],
    rel: ["fitts", "miller", "weber-fechner"],
    sim: "sim-hick"
  },
  {
    id: "fitts",
    nombre: "Ley de Fitts",
    autor: "Paul Fitts",
    anio: "1954",
    cat: "psi",
    enunciado: "El tiempo para alcanzar un objetivo depende de la distancia hasta él y de su tamaño.",
    explicacion: "Cuanto más lejos y más pequeño el objetivo, más se tarda: el tiempo crece con log₂(2D/W). Gobierna cada clic, cada botón táctil y cada movimiento de mano. De aquí salen reglas de diseño: botones frecuentes grandes y cerca, esquinas de pantalla 'infinitamente' fáciles de alcanzar.",
    ejemplo: "Cerrar una ventana es fácil porque la X está en la esquina (tamaño efectivo infinito); acertar en un enlace diminuto entre otros enlaces es la peor tarea que ofrece una interfaz.",
    tags: ["movimiento", "objetivos", "botones", "interfaces", "UX", "diseño"],
    rel: ["hick", "weber-fechner"],
    sim: "sim-fitts"
  },
  {
    id: "efecto-thorndike",
    nombre: "Ley del efecto",
    autor: "Edward Thorndike",
    anio: "1911",
    cat: "psi",
    enunciado: "Las conductas seguidas de consecuencias agradables tienden a repetirse; las seguidas de consecuencias molestas, a extinguirse.",
    explicacion: "Formulada con gatos que aprendían a escapar de cajas-problema, es la semilla del conductismo y del condicionamiento operante de Skinner. Toda economía de recompensas —propinas, 'me gusta', bonificaciones, notificaciones— descansa sobre esta ley.",
    ejemplo: "Si revisar el teléfono trae de vez en cuando una notificación gratificante, la conducta de revisar se dispara: es la misma mecánica de la máquina tragaperras.",
    tags: ["conducta", "refuerzo", "aprendizaje", "condicionamiento", "hábitos"],
    rel: ["practica", "yerkes-dodson"]
  },
  {
    id: "practica",
    nombre: "Ley de la práctica",
    autor: "Arthur Snoddy; Newell y Rosenbloom",
    anio: "1926",
    cat: "psi",
    enunciado: "La velocidad de ejecución de una tarea mejora con la práctica siguiendo una curva de rendimientos decrecientes.",
    explicacion: "Las primeras repeticiones producen mejoras enormes; después, cada duplicación de la práctica arranca solo una fracción constante de mejora (ley potencial). Explica por qué pasar de novato a competente es rápido y de experto a élite cuesta años.",
    ejemplo: "En una semana aprendes a teclear el doble de rápido; ganar esa misma proporción otra vez requiere meses. Igual con un instrumento, un idioma o un deporte.",
    tags: ["práctica", "aprendizaje", "habilidad", "expertos"],
    rel: ["wright", "efecto-thorndike", "ebbinghaus"]
  },
  {
    id: "miller",
    nombre: "Ley de Miller (el mágico número 7±2)",
    autor: "George Miller",
    anio: "1956",
    cat: "psi",
    enunciado: "La memoria de trabajo retiene unos 7 (±2) elementos a la vez.",
    explicacion: "Miller observó ese límite en tareas de retención inmediata; investigación posterior lo rebaja a 4±1 'trozos' (chunks). La clave es el chunking: agrupar elementos en unidades con significado multiplica la capacidad efectiva. Es la razón de que los teléfonos se escriban por bloques.",
    ejemplo: "601-555-8974 se recuerda; 6015558974 no. Un ajedrecista experto recuerda un tablero entero porque lo ve como 5 estructuras, no como 32 piezas sueltas.",
    tags: ["memoria", "atención", "chunking", "límites cognitivos"],
    rel: ["hick", "ebbinghaus"]
  },
  {
    id: "ebbinghaus",
    nombre: "Curva del olvido de Ebbinghaus",
    autor: "Hermann Ebbinghaus",
    anio: "1885",
    cat: "psi",
    enunciado: "Lo aprendido se olvida de forma exponencial: la mayor pérdida ocurre en las primeras horas y días.",
    explicacion: "Ebbinghaus, memorizando sílabas sin sentido sobre sí mismo, midió que sin repaso se pierde gran parte de lo aprendido en 24 horas. Cada repaso espaciado aplana la curva: es la base científica de la repetición espaciada usada por las mejores aplicaciones de estudio.",
    ejemplo: "Estudiar 4 veces 15 minutos repartidos en dos semanas fija más vocabulario que una sesión única de 2 horas la víspera del examen.",
    tags: ["memoria", "olvido", "repaso", "estudio", "repetición espaciada"],
    rel: ["miller", "practica"],
    sim: "sim-olvido"
  },
  {
    id: "dunning-kruger",
    nombre: "Efecto Dunning-Kruger",
    autor: "David Dunning y Justin Kruger",
    anio: "1999",
    cat: "psi",
    enunciado: "Quien menos sabe tiende a sobreestimar su competencia, porque le faltan los conocimientos para notar sus propios errores.",
    explicacion: "La incompetencia es doble: impide hacerlo bien e impide darse cuenta. Los expertos, en cambio, tienden a subestimarse (asumen que lo fácil para ellos es fácil para todos). La popular curva del 'monte de la estupidez' es una caricatura del hallazgo, pero captura la experiencia de aprender: confianza inicial, desplome al descubrir la profundidad del tema, y recuperación lenta.",
    ejemplo: "Tras un vídeo de 20 minutos sobre inversión, alguien se siente listo para gestionar sus ahorros; tras veinte años de experiencia, un gestor profesional habla con cautela de lo difícil que es batir al mercado.",
    tags: ["sesgo", "confianza", "competencia", "metacognición", "humildad"],
    rel: ["amara", "twyman", "cunningham"],
    sim: "sim-dunning"
  },
  {
    id: "gestalt",
    nombre: "Leyes de la Gestalt",
    autor: "Max Wertheimer, Kurt Koffka, Wolfgang Köhler",
    anio: "1923",
    cat: "psi",
    enunciado: "La percepción organiza los estímulos en conjuntos con significado: el todo es distinto de la suma de las partes.",
    explicacion: "Familia de principios sobre cómo agrupamos lo que vemos: proximidad (lo cercano forma grupo), semejanza (lo parecido va junto), cierre (completamos figuras incompletas), continuidad, figura-fondo y destino común. Todo diseño gráfico y de interfaces las aplica, las conozca o no.",
    ejemplo: "Tres puntos y una curva se ven como una cara. En un formulario, la etiqueta pegada a su campo se entiende sin flechas ni bordes: pura proximidad.",
    tags: ["percepción", "diseño", "agrupación", "figura-fondo", "visual"],
    rel: ["weber-fechner", "fitts"]
  },
  {
    id: "hebb",
    nombre: "Ley de Hebb",
    autor: "Donald Hebb",
    anio: "1949",
    cat: "psi",
    enunciado: "Las neuronas que se activan juntas, se conectan entre sí.",
    explicacion: "Cuando una neurona contribuye repetidamente a activar a otra, la conexión entre ambas se refuerza. Es el mecanismo básico de la plasticidad sináptica y del aprendizaje: la experiencia esculpe físicamente el cerebro. Inspiró las redes neuronales artificiales.",
    ejemplo: "Asociar el olor del café con la mañana, o que un acorde evoque un recuerdo: circuitos que se activaron juntos tantas veces que ahora uno dispara al otro.",
    tags: ["neuronas", "plasticidad", "aprendizaje", "cerebro", "sinapsis"],
    rel: ["practica", "ebbinghaus"]
  },

  /* ======================= SOCIOLOGÍA Y COMUNICACIÓN ======================= */
  {
    id: "campbell",
    nombre: "Ley de Campbell",
    autor: "Donald T. Campbell",
    anio: "1976",
    cat: "soc",
    enunciado: "Cuanto más se usa un indicador social para tomar decisiones, más presión sufre para corromperse y más corrompe los procesos que pretende medir.",
    explicacion: "Es la hermana sociológica de la ley de Goodhart, formulada de forma independiente y centrada en políticas públicas: exámenes, estadísticas de criminalidad, listas de espera. El indicador no solo se falsea: deforma la actividad real, porque todos trabajan 'para el número'.",
    ejemplo: "Cuando el sueldo de las escuelas depende de exámenes estandarizados, la enseñanza se convierte en entrenamiento para el examen y florecen las trampas; el indicador sube mientras la educación real se empobrece.",
    tags: ["indicadores", "políticas públicas", "evaluación", "corrupción", "educación"],
    rel: ["goodhart", "michels"]
  },
  {
    id: "michels",
    nombre: "Ley de hierro de la oligarquía",
    autor: "Robert Michels",
    anio: "1911",
    cat: "soc",
    enunciado: "Toda organización, por democrática que nazca, acaba gobernada por una minoría dirigente.",
    explicacion: "La organización exige delegación, burocracia y liderazgo experto; los líderes acumulan información, contactos y control del aparato, y su prioridad pasa a ser conservar el poder. Michels lo demostró estudiando precisamente a los partidos socialistas más igualitarios de su época: 'quien dice organización, dice oligarquía'.",
    ejemplo: "Sindicatos, partidos, colegios profesionales y hasta asociaciones vecinales donde 'los de siempre' llevan décadas en la directiva pese a estatutos impecablemente democráticos.",
    tags: ["poder", "élites", "burocracia", "democracia", "organizaciones"],
    rel: ["pournelle", "parkinson", "campbell"]
  },
  {
    id: "duverger",
    nombre: "Ley de Duverger",
    autor: "Maurice Duverger",
    anio: "1951",
    cat: "soc",
    enunciado: "El sistema electoral de mayoría simple a una vuelta tiende al bipartidismo; la representación proporcional, al multipartidismo.",
    explicacion: "Con mayoría simple, votar a un partido pequeño es 'tirar el voto', así que votantes y donantes se concentran en los dos grandes (efecto psicológico), y los pequeños no obtienen escaños (efecto mecánico). Es de las pocas generalizaciones de la ciencia política con rango de ley.",
    ejemplo: "Estados Unidos y Reino Unido (mayoría simple): dos partidos dominantes durante siglos. Países con sistemas proporcionales: parlamentos con cinco o más partidos y gobiernos de coalición.",
    tags: ["elecciones", "partidos", "voto", "sistemas electorales", "política"],
    rel: ["hotelling", "michels"]
  },
  {
    id: "godwin",
    nombre: "Ley de Godwin",
    autor: "Mike Godwin",
    anio: "1990",
    cat: "soc",
    enunciado: "A medida que una discusión en línea se alarga, la probabilidad de una comparación con Hitler o los nazis se acerca a uno.",
    explicacion: "Nació como experimento de 'memética defensiva': Godwin quería que la gente reconociera el patrón y se avergonzara de banalizar el Holocausto como arma retórica. Por convención, quien recurre a la comparación pierde el debate. Describe la escalada retórica de toda discusión acalorada.",
    ejemplo: "Un hilo sobre normas de tráfico urbano que a los cien comentarios ya compara el carril bici con el fascismo.",
    tags: ["internet", "debate", "foros", "retórica", "escalada"],
    rel: ["poe", "brandolini", "sayre"]
  },
  {
    id: "poe",
    nombre: "Ley de Poe",
    autor: "Nathan Poe",
    anio: "2005",
    cat: "soc",
    enunciado: "Sin una señal clara de ironía, una parodia del extremismo es indistinguible del extremismo auténtico.",
    explicacion: "Y a la inversa: las posturas extremas sinceras parecen parodia. En texto plano, sin gesto ni tono, la sátira más exagerada siempre encontrará quien la tome en serio, y la opinión más disparatada, quien la crea broma. Es un problema estructural de la comunicación escrita en internet, y el motor de mucha desinformación.",
    ejemplo: "Cuentas satíricas citadas como noticias reales por medios serios, y comunicados auténticos que los lectores descartan por 'demasiado absurdos para ser verdad'.",
    tags: ["parodia", "sátira", "internet", "extremismo", "desinformación"],
    rel: ["godwin", "betteridge", "brandolini"]
  },
  {
    id: "cunningham",
    nombre: "Ley de Cunningham",
    autor: "Ward Cunningham (atribuida por Steven McGeady)",
    anio: "2010",
    cat: "soc",
    enunciado: "La mejor manera de obtener la respuesta correcta en internet no es preguntar, sino publicar la respuesta incorrecta.",
    explicacion: "Corregir a otros motiva más que ayudar: una pregunta puede ignorarse, pero un error clama ser enmendado. Nombrada en honor al inventor del wiki (aunque el propio Cunningham reniega de ella), captura una verdad incómoda sobre la psicología de los foros y el conocimiento colaborativo.",
    ejemplo: "Preguntas '¿cómo configuro este servidor?' y nadie contesta; escribes 'este servidor no se puede configurar sin pagar licencia' y en minutos tres expertos te explican, indignados, exactamente cómo hacerlo gratis.",
    tags: ["internet", "foros", "wiki", "conocimiento", "corrección"],
    rel: ["linus", "brandolini", "dunning-kruger"]
  },
  {
    id: "brandolini",
    nombre: "Ley de Brandolini (asimetría de la desinformación)",
    autor: "Alberto Brandolini",
    anio: "2013",
    cat: "soc",
    enunciado: "Refutar una tontería exige un orden de magnitud más de energía que producirla.",
    explicacion: "Inventar un bulo es gratis; desmontarlo exige documentarse, redactar, citar fuentes y aun así llegar tarde y a menos gente. Esta asimetría estructural explica por qué la desinformación siempre va por delante de los desmentidos y por qué los verificadores de datos nunca dan abasto.",
    ejemplo: "Un tuit falso de diez palabras sobre una vacuna se comparte cien mil veces; el informe técnico que lo refuta, con veinte referencias, lo leen unos cientos.",
    tags: ["bulos", "desinformación", "verificación", "redes sociales"],
    rel: ["cunningham", "poe", "godwin", "twyman"]
  },
  {
    id: "betteridge",
    nombre: "Ley de titulares de Betteridge",
    autor: "Ian Betteridge",
    anio: "2009",
    cat: "soc",
    enunciado: "Todo titular que termina en signo de interrogación puede responderse con un 'no'.",
    explicacion: "Si el periodista tuviera pruebas de que la respuesta es 'sí', lo afirmaría en el titular. La pregunta es el recurso para publicar una especulación jugosa sin comprometerse ni exponerse a demandas. No es una ley infalible, sino un detector de periodismo especulativo sorprendentemente fiable.",
    ejemplo: "'¿Es este el fin del dinero en efectivo?' — no. '¿Ha encontrado la NASA vida extraterrestre?' — no; si la hubiera encontrado, el titular sería 'La NASA encuentra vida extraterrestre'.",
    tags: ["prensa", "titulares", "clickbait", "periodismo", "escepticismo"],
    rel: ["brandolini", "poe", "twyman"]
  },
  {
    id: "sayre",
    nombre: "Ley de Sayre",
    autor: "Wallace Sayre",
    anio: "c. 1973",
    cat: "soc",
    enunciado: "En toda disputa, la intensidad de las emociones es inversamente proporcional a lo que está en juego.",
    explicacion: "Formulada sobre la política universitaria ('las disputas académicas son tan feroces precisamente porque hay tan poco en juego'). Cuando lo sustantivo es menor, la disputa se vuelve identitaria: se pelea por estatus y orgullo, no por consecuencias, y eso desata las pasiones más feroces.",
    ejemplo: "Una comunidad de vecinos dividida en guerra civil por el color de los buzones, mientras aprueba sin debate una derrama millonaria.",
    tags: ["conflicto", "academia", "estatus", "emociones", "debate"],
    rel: ["trivialidad", "godwin"]
  },
  {
    id: "sturgeon",
    nombre: "Ley de Sturgeon",
    autor: "Theodore Sturgeon",
    anio: "1956",
    cat: "soc",
    enunciado: "El noventa por ciento de todo es basura.",
    explicacion: "El escritor de ciencia ficción respondía a quienes despreciaban su género: sí, el 90% de la ciencia ficción es mala... como el 90% de todo lo demás. Juzgar un campo por su peor mayoría es un error de muestreo; lo justo es comparar lo mejor de cada campo. También consuela al creador: la abundancia de mediocridad es el estado natural de cualquier disciplina.",
    ejemplo: "El 90% de las películas, los artículos científicos, las startups y los vinos son olvidables, y no por ello el cine, la ciencia, el emprendimiento o la enología carecen de valor: se definen por su mejor 10%.",
    tags: ["calidad", "crítica", "ciencia ficción", "mediocridad", "criterio"],
    rel: ["pareto", "gresham", "price"],
    sim: "sim-sturgeon"
  },
  {
    id: "hanlon",
    nombre: "Navaja de Hanlon",
    autor: "Robert J. Hanlon",
    anio: "1980",
    cat: "soc",
    enunciado: "Nunca atribuyas a la maldad lo que se explica adecuadamente por la torpeza.",
    explicacion: "Heurística para interpretar agravios: la incompetencia, la prisa, el malentendido y el descuido son enormemente más frecuentes que la conspiración. Ahorra rencores infundados y diagnósticos erróneos. Con corolario prudente: no descartes la maldad cuando la 'torpeza' se repite siempre en beneficio del mismo.",
    ejemplo: "El compañero que no te copió en el correo importante casi seguro se olvidó; suponer una maniobra en tu contra envenena la relación y suele ser falso.",
    tags: ["atribución", "malicia", "incompetencia", "heurística", "conflicto"],
    rel: ["occam", "murphy"]
  },
  {
    id: "occam",
    nombre: "Navaja de Occam",
    autor: "Guillermo de Ockham",
    anio: "siglo XIV",
    cat: "soc",
    enunciado: "En igualdad de condiciones, la explicación más simple suele ser la correcta.",
    explicacion: "Formalmente: no multipliques entidades sin necesidad. Entre hipótesis que explican igual de bien los hechos, elige la que menos supuestos exija. No garantiza la verdad —a veces la realidad es enrevesada—, pero es la mejor política de apuestas y el antídoto clásico contra las teorías conspirativas de relojería.",
    ejemplo: "Si las luces de casa no encienden, 'se fue la luz' gana a 'un apagón selectivo provocado para perjudicarme'. En medicina: 'cuando oigas cascos, piensa en caballos, no en cebras'.",
    tags: ["parsimonia", "hipótesis", "filosofía", "método científico", "simplicidad"],
    rel: ["hanlon", "sutton", "gall"]
  },
  {
    id: "tres-estadios",
    nombre: "Ley de los tres estadios",
    autor: "Auguste Comte",
    anio: "1842",
    cat: "soc",
    enunciado: "El conocimiento humano pasa por tres fases: teológica, metafísica y positiva (científica).",
    explicacion: "Para el fundador de la sociología, cada rama del saber explica primero el mundo por voluntades divinas, luego por esencias abstractas y finalmente por leyes verificables. Hoy se considera un esquema demasiado lineal, pero es una pieza fundacional del positivismo y de la propia idea de 'ciencia social'.",
    ejemplo: "La explicación de la peste: castigo divino (teológica), 'miasmas' y desequilibrios de humores (metafísica), teoría microbiana verificada (positiva).",
    tags: ["positivismo", "historia", "ciencia", "sociología", "Comte"],
    rel: ["occam", "stigler"]
  },
  {
    id: "dunbar",
    nombre: "Número de Dunbar",
    autor: "Robin Dunbar",
    anio: "1992",
    cat: "soc",
    enunciado: "El ser humano solo puede mantener unas 150 relaciones sociales estables.",
    explicacion: "Extrapolado del tamaño del neocórtex de los primates: nuestro cerebro pone un techo cognitivo a las relaciones que podemos sostener con historia y confianza mutuas. Aparecen capas: ~5 íntimos, ~15 cercanos, ~50 amigos, ~150 conocidos significativos. Los grupos humanos funcionales (aldeas, compañías militares, empresas) tienden a fragmentarse al superar esa cifra.",
    ejemplo: "Puedes tener 3000 seguidores, pero la lista de personas a las que llamarías en una crisis, o que notarían tu ausencia, ronda las mismas 150 de una aldea neolítica.",
    tags: ["relaciones", "grupos", "cerebro", "redes sociales", "comunidad"],
    rel: ["metcalfe", "michels"]
  },

  /* ======================= GESTIÓN Y ORGANIZACIONES ======================= */
  {
    id: "parkinson",
    nombre: "Ley de Parkinson",
    autor: "Cyril Northcote Parkinson",
    anio: "1955",
    cat: "ges",
    enunciado: "El trabajo se expande hasta llenar todo el tiempo disponible para terminarlo.",
    explicacion: "Publicada como sátira en The Economist tras observar la burocracia naval británica: los plazos holgados no producen calidad, producen dilación, perfeccionismo estéril y tareas infladas. Corolarios célebres: el gasto crece hasta igualar los ingresos, y los datos se expanden hasta llenar el disco. Su reverso es útil: plazos ajustados (realistas) concentran el esfuerzo.",
    ejemplo: "Un informe con un mes de plazo ocupa el mes entero —tres semanas de aplazamiento incluido—; el mismo informe con tres días de plazo, sale en tres días con calidad similar.",
    tags: ["tiempo", "plazos", "procrastinación", "burocracia", "productividad"],
    rel: ["hofstadter", "trivialidad", "pournelle", "brooks"],
    sim: "sim-parkinson"
  },
  {
    id: "trivialidad",
    nombre: "Ley de la trivialidad (efecto bikeshedding)",
    autor: "Cyril Northcote Parkinson",
    anio: "1957",
    cat: "ges",
    enunciado: "El tiempo dedicado a cada punto del orden del día es inversamente proporcional a su importancia.",
    explicacion: "Un comité aprueba en minutos un reactor nuclear (nadie lo entiende, nadie osa opinar) y debate horas el cobertizo para bicicletas (todos tienen opinión sobre cobertizos). Opinamos donde nos sentimos competentes, no donde importa. Conocerla permite detectar y cortar el 'bikeshedding' en reuniones.",
    ejemplo: "Una reunión que aprueba sin debate un presupuesto de dos millones y dedica cuarenta minutos al color del logotipo o al proveedor del café.",
    tags: ["reuniones", "comités", "prioridades", "bikeshedding", "decisiones"],
    rel: ["parkinson", "sayre"]
  },
  {
    id: "peter",
    nombre: "Principio de Peter",
    autor: "Laurence J. Peter",
    anio: "1969",
    cat: "ges",
    enunciado: "En una jerarquía, todo empleado tiende a ascender hasta su nivel de incompetencia.",
    explicacion: "Se asciende a quien hace bien su trabajo actual... hasta llegar a un puesto que ya no hace bien, donde se queda. Con el tiempo, cada puesto tiende a ser ocupado por alguien incapaz de desempeñarlo, y el trabajo real lo hacen quienes aún no han alcanzado su nivel de incompetencia. El error de fondo: premiar el rendimiento pasado con un trabajo distinto.",
    ejemplo: "El mejor vendedor asciende a jefe de ventas: se pierde un vendedor excelente y se gana un gestor mediocre, porque vender y dirigir vendedores son oficios diferentes.",
    tags: ["jerarquía", "ascensos", "incompetencia", "carrera", "empresa"],
    rel: ["dilbert", "pournelle", "michels"]
  },
  {
    id: "dilbert",
    nombre: "Principio de Dilbert",
    autor: "Scott Adams",
    anio: "1995",
    cat: "ges",
    enunciado: "Las empresas tienden a ascender a sus empleados menos competentes a puestos directivos para limitar el daño que pueden causar.",
    explicacion: "Versión satírica y cínica del principio de Peter: si el trabajo real lo hacen ingenieros, vendedores y operarios, el lugar menos dañino para el inepto es... la gestión intermedia, donde solo hará organigramas y reuniones. Es humor, pero con un fondo serio sobre la desconexión entre jerarquía y creación de valor.",
    ejemplo: "El clásico jefe de la tira cómica de Dilbert: incapaz de tareas técnicas, experto en palabrería de gestión, y aun así por encima de quienes construyen el producto.",
    tags: ["gestión", "sátira", "ascensos", "jerarquía", "humor"],
    rel: ["peter", "pournelle", "parkinson"]
  },
  {
    id: "pournelle",
    nombre: "Ley de hierro de la burocracia (Ley de Pournelle)",
    autor: "Jerry Pournelle",
    anio: "c. 1975",
    cat: "ges",
    enunciado: "En toda burocracia acaban mandando quienes trabajan para la organización misma, no quienes trabajan para sus fines.",
    explicacion: "Toda organización tiene dos tipos de personas: las dedicadas a la misión (el maestro que enseña, el médico que cura) y las dedicadas a la organización (comités, normativa, presupuesto, poder interno). La segunda clase controla los ascensos, las reglas y los recursos, así que inevitablemente toma el mando, y la misión pasa a segundo plano.",
    ejemplo: "Un sistema educativo donde los mejores sueldos y despachos no son de quien da clase sino de capas administrativas crecientes, y donde el papeleo le roba al maestro las horas de enseñar.",
    tags: ["burocracia", "poder", "instituciones", "misión", "administración"],
    rel: ["michels", "parkinson", "peter"]
  },
  {
    id: "murphy",
    nombre: "Ley de Murphy",
    autor: "Edward A. Murphy Jr.",
    anio: "1949",
    cat: "ges",
    enunciado: "Si algo puede salir mal, saldrá mal.",
    explicacion: "Nació en pruebas de cohetes de la Fuerza Aérea de EE. UU.: un sensor podía montarse de dos maneras y un técnico lo montó al revés. Su lectura seria es un principio de ingeniería defensiva: si un diseño permite el error, con suficientes repeticiones el error ocurrirá; diséñalo para que el error sea imposible. La lectura popular (pesimismo cósmico) olvida su origen: no es fatalismo, es estadística más diseño.",
    ejemplo: "Si un conector USB cabe al revés, alguien lo meterá al revés: por eso los conectores modernos son reversibles. La tostada cae del lado de la mantequilla las veces suficientes para fundar una ley.",
    tags: ["errores", "diseño", "ingeniería", "prevención", "pesimismo"],
    rel: ["hanlon", "sod", "gall"]
  },
  {
    id: "segal",
    nombre: "Ley de Segal",
    autor: "anónimo (atribución publicitaria)",
    anio: "c. 1930",
    cat: "ges",
    enunciado: "Quien tiene un reloj sabe qué hora es; quien tiene dos, nunca está seguro.",
    explicacion: "Más información no siempre es mejor decisión: dos fuentes discrepantes sin criterio para arbitrar generan menos certeza que una sola. En ingeniería es literal (por eso los sistemas críticos llevan tres sensores y votan por mayoría, nunca dos). En la vida: multiplicar opiniones, métricas o diagnósticos sin jerarquía de confianza paraliza.",
    ejemplo: "Dos básculas que difieren en un kilo, dos previsiones del tiempo opuestas, dos médicos con diagnósticos distintos: la segunda fuente no sumó conocimiento, restó certeza.",
    tags: ["información", "decisión", "redundancia", "certeza", "sensores"],
    rel: ["twyman", "occam"]
  },
  {
    id: "illich",
    nombre: "Ley de Illich (de la productividad negativa)",
    autor: "Ivan Illich",
    anio: "1973",
    cat: "ges",
    enunciado: "Pasado cierto umbral de horas, seguir trabajando disminuye —y llega a invertir— la productividad.",
    explicacion: "Illich lo llamó 'contraproductividad': toda herramienta o esfuerzo, pasado un umbral, se vuelve contra su propio fin. Aplicado al trabajo: tras demasiadas horas, el rendimiento marginal es negativo (los errores cometidos cuestan más que lo producido). Las jornadas heroicas sostenidas producen menos que las jornadas razonables.",
    ejemplo: "Estudios en industria y hospitales: a partir de cierto número de horas semanales sostenidas, la producción total apenas supera a la de jornadas menores, y los errores y accidentes se disparan. La hora catorce de un turno resta.",
    tags: ["fatiga", "horas", "descanso", "rendimiento", "burnout"],
    rel: ["yerkes-dodson", "parkinson", "rendimientos-decrecientes"]
  },
  {
    id: "price",
    nombre: "Ley de Price",
    autor: "Derek de Solla Price",
    anio: "1963",
    cat: "ges",
    enunciado: "La mitad del trabajo de un campo la realiza la raíz cuadrada del número de participantes.",
    explicacion: "Si 100 investigadores publican en un área, unos 10 firman la mitad de los artículos. Es una asimetría aún más brutal que la de Pareto y crece con el tamaño del grupo: en una empresa de 10 000 personas, la mitad del impacto vendría de unas 100. Recuerda que el talento y la contribución no se distribuyen en absoluto de manera uniforme.",
    ejemplo: "En un equipo de 9 desarrolladores, unos 3 escriben la mitad del código útil; en la música, un puñado de compositores firma la mitad del repertorio que se interpreta.",
    tags: ["productividad", "desigualdad", "ciencia", "talento", "contribución"],
    rel: ["pareto", "sturgeon", "zipf"]
  },
  {
    id: "hofstadter",
    nombre: "Ley de Hofstadter",
    autor: "Douglas Hofstadter",
    anio: "1979",
    cat: "ges",
    enunciado: "Todo lleva más tiempo del previsto, incluso teniendo en cuenta la ley de Hofstadter.",
    explicacion: "Es recursiva a propósito: conocer nuestro optimismo crónico no lo cura. Conecta con la 'falacia de planificación' de Kahneman: planificamos el mejor caso, ignorando imprevistos que, individualmente improbables, son colectivamente seguros. Remedio parcial: estimar mirando cuánto tardaron proyectos similares (vista externa), no imaginando los pasos del propio (vista interna).",
    ejemplo: "La reforma de la cocina presupuestada en seis semanas que dura cuatro meses, la tesis 'de un año' que dura tres, el videojuego retrasado dos veces... por un estudio que ya contaba con retrasarse.",
    tags: ["planificación", "plazos", "estimación", "optimismo", "proyectos"],
    rel: ["parkinson", "brooks", "murphy"]
  },
  {
    id: "sod",
    nombre: "Ley de Sod",
    autor: "sabiduría popular británica",
    anio: "tradicional",
    cat: "ges",
    enunciado: "Lo que puede salir mal, saldrá mal, y además en el peor momento posible.",
    explicacion: "La variante británica y más pesimista de la ley de Murphy: añade la puntería del desastre. Su núcleo racional es el sesgo de memoria (recordamos los fallos inoportunos, olvidamos los inocuos) más un hecho real: los sistemas se estresan a la vez —el tráfico, la lluvia y tu prisa correlacionan—, así que los fallos se agolpan en los peores momentos.",
    ejemplo: "La impresora funciona todo el año y se atasca el día de la entrega; el semáforo se pone rojo justo cuando llegas tarde. No es magia: ese día imprimías más, salías más justo y lo recordarás más.",
    tags: ["pesimismo", "fallos", "humor", "sesgo de memoria"],
    rel: ["murphy", "littlewood"]
  },

  /* ======================= ESTADÍSTICA Y DATOS ======================= */
  {
    id: "benford",
    nombre: "Ley de Benford",
    autor: "Simon Newcomb; Frank Benford",
    anio: "1881 / 1938",
    cat: "est",
    enunciado: "En muchos conjuntos de datos reales, el primer dígito es 1 casi un tercio de las veces, y cada dígito mayor es menos frecuente.",
    explicacion: "Los datos que crecen multiplicativamente y abarcan varios órdenes de magnitud (poblaciones, facturas, ríos, constantes físicas) pasan más 'tiempo' empezando por 1 que por 9: la frecuencia sigue log₁₀(1+1/d). Los números inventados por humanos no cumplen el patrón, lo que la convierte en herramienta forense contra fraudes contables y electorales.",
    ejemplo: "Hacienda y los auditores comparan los primeros dígitos de miles de facturas con la curva de Benford: una empresa que inventa gastos tiende a repartir los dígitos uniformemente y salta la alarma.",
    tags: ["fraude", "dígitos", "auditoría", "forense", "distribuciones"],
    rel: ["zipf", "grandes-numeros"],
    sim: "sim-benford"
  },
  {
    id: "zipf",
    nombre: "Ley de Zipf",
    autor: "George Kingsley Zipf",
    anio: "1935",
    cat: "est",
    enunciado: "En un idioma, la palabra más frecuente aparece el doble que la segunda, el triple que la tercera: la frecuencia es inversa al rango.",
    explicacion: "Un puñado de palabras ('de', 'la', 'que') domina todo texto, mientras miles apenas aparecen. El mismo patrón rige tamaños de ciudades, visitas web, apellidos y terremotos. Emerge, se cree, del equilibrio entre el mínimo esfuerzo del hablante (pocas palabras comodín) y del oyente (palabras precisas).",
    ejemplo: "En español, unas 100 palabras cubren la mitad de cualquier conversación: por eso las primeras semanas estudiando un idioma rinden tanto. La mayor ciudad de un país suele doblar a la segunda.",
    tags: ["lenguaje", "frecuencia", "rango", "ciudades", "distribuciones"],
    rel: ["pareto", "benford", "price"],
    sim: "sim-zipf"
  },
  {
    id: "grandes-numeros",
    nombre: "Ley de los grandes números",
    autor: "Jacob Bernoulli",
    anio: "1713",
    cat: "est",
    enunciado: "Al repetir un experimento aleatorio muchas veces, el promedio observado se acerca al valor esperado.",
    explicacion: "El azar es indomable en corto y disciplinado en largo: diez lanzamientos de moneda pueden dar 8 caras, pero diez mil no se alejarán del 50%. Es la razón de que existan casinos y aseguradoras (ellos juegan la partida larga; el cliente, la corta). Ojo con su malinterpretación, la 'falacia del jugador': la moneda no tiene memoria ni deudas que saldar.",
    ejemplo: "Un casino puede perder contra un cliente cualquier noche; contra un millón de apuestas, su ventaja del 2,7% en la ruleta es una certeza contable.",
    tags: ["azar", "probabilidad", "promedios", "casinos", "convergencia"],
    rel: ["regresion-media", "littlewood", "benford"],
    sim: "sim-grandes"
  },
  {
    id: "regresion-media",
    nombre: "Regresión a la media",
    autor: "Francis Galton",
    anio: "1886",
    cat: "est",
    enunciado: "Tras un resultado extremo, el siguiente tiende a acercarse al promedio.",
    explicacion: "Todo resultado combina capacidad y suerte; un extremo suele llevar suerte extrema, que no se repite. Genera ilusiones peligrosas: el castigo 'funciona' (tras un desastre se mejora igual) y el elogio 'falla' (tras una genialidad se empeora igual), cuando solo es el azar volviendo a su cauce. Es de los sesgos que más decisiones médicas, educativas y deportivas contamina.",
    ejemplo: "La 'maldición' de la portada deportiva: el jugador sale en portada tras una racha irrepetible, y lo que sigue es su nivel normal. El remedio milagroso tomado en el pico del dolor 'cura' porque el dolor iba a remitir de todos modos.",
    tags: ["azar", "extremos", "sesgos", "evaluación", "deporte"],
    rel: ["grandes-numeros", "twyman", "dunning-kruger"],
    sim: "sim-regresion"
  },
  {
    id: "littlewood",
    nombre: "Ley de Littlewood (de los milagros)",
    autor: "John E. Littlewood",
    anio: "1986",
    cat: "est",
    enunciado: "Una persona corriente presencia un 'milagro' (suceso de probabilidad una en un millón) aproximadamente una vez al mes.",
    explicacion: "El cálculo del matemático: percibimos ~1 suceso por segundo durante ~8 horas al día; en un mes son más de un millón de sucesos, así que lo de 'una vez en un millón' toca mensualmente. Las coincidencias asombrosas no requieren explicación sobrenatural: con suficientes oportunidades, lo improbable es rutinario.",
    ejemplo: "Piensas en alguien y llama a los cinco minutos. Asombroso, hasta que cuentas cuántas veces piensas en personas que no llaman: con millones de 'ensayos', la coincidencia era matemáticamente obligatoria.",
    tags: ["coincidencias", "milagros", "probabilidad", "escepticismo"],
    rel: ["grandes-numeros", "sod", "regresion-media"]
  },
  {
    id: "twyman",
    nombre: "Ley de Twyman",
    autor: "Tony Twyman",
    anio: "c. 1970",
    cat: "est",
    enunciado: "Cuanto más interesante o inusual parece un dato, más probable es que sea un error.",
    explicacion: "Nacida en la medición de audiencias: los picos espectaculares solían ser fallos del medidor. Los datos sorprendentes tienen dos explicaciones —el mundo cambió o la medición falló— y la segunda es casi siempre la cierta. Regla práctica de todo analista: la cifra que te haría famoso merece triple verificación antes que celebración.",
    ejemplo: "El gráfico de ventas se dispara un 400% el martes: antes de descorchar nada, revisa si el martes se duplicó la base de datos. El 'gen de la inteligencia' portada de revistas rara vez sobrevive a la replicación.",
    tags: ["datos", "errores", "análisis", "escepticismo", "verificación"],
    rel: ["goodhart", "betteridge", "segal", "regresion-media"]
  },
  {
    id: "stigler",
    nombre: "Ley de la eponimia de Stigler",
    autor: "Stephen Stigler",
    anio: "1980",
    cat: "est",
    enunciado: "Ningún descubrimiento científico lleva el nombre de su verdadero descubridor.",
    explicacion: "Los créditos van al que populariza, no al pionero: la ley de Benford la halló Newcomb, la campana de Gauss la usó antes De Moivre, el teorema de Pitágoras era babilónico. Y en un giro deliberado, Stigler atribuyó su propia ley a Robert Merton, cumpliéndola en el acto de enunciarla.",
    ejemplo: "Media docena de leyes de este mismo catálogo la cumplen: Benford (Newcomb), Gresham (ya descrita por Copérnico y Oresme), Zipf (precedida por Estoup) o Pareto (formalizada por Lorenz y otros).",
    tags: ["ciencia", "epónimos", "historia", "crédito", "humor"],
    rel: ["benford", "gresham", "tres-estadios"]
  },
  {
    id: "berkson",
    nombre: "Paradoja de Berkson",
    autor: "Joseph Berkson",
    anio: "1946",
    cat: "est",
    enunciado: "Seleccionar una muestra por un criterio común crea correlaciones falsas entre causas independientes.",
    explicacion: "Si en un hospital solo ingresan pacientes con al menos una enfermedad grave, entre los ingresados dos enfermedades independientes parecerán correlacionadas negativamente (tener una 'explica' el ingreso sin necesitar la otra). Este sesgo de selección fabrica asociaciones ilusorias en medicina, en admisiones y en la vida diaria.",
    ejemplo: "'Los actores guapos actúan peor': falso en la población general, cierto en la muestra de actores famosos, porque para ser famoso basta destacar en belleza o en talento. La correlación la creó el filtro de la fama, no la realidad.",
    tags: ["sesgo de selección", "correlación", "epidemiología", "muestras"],
    rel: ["twyman", "regresion-media", "cuidados-inversos"]
  },

  /* ======================= MEDICINA Y FISIOLOGÍA ======================= */
  {
    id: "sutton",
    nombre: "Ley de Sutton",
    autor: "William Dock (por el atracador Willie Sutton)",
    anio: "años 1960",
    cat: "med",
    enunciado: "Ante un diagnóstico, ve primero 'donde está el dinero': la hipótesis más probable.",
    explicacion: "Al atracador Willie Sutton se le atribuye responder, sobre por qué robaba bancos: 'porque ahí está el dinero'. En medicina ordena el diagnóstico: pide primero la prueba que con más probabilidad confirmará la causa más frecuente, en lugar de un despliegue exhaustivo de pruebas raras. Es la navaja de Occam con bata y presupuesto.",
    ejemplo: "Tos, fiebre y dolor torácico: radiografía de tórax buscando neumonía, no resonancia buscando un tumor raro. Primero los caballos; las cebras, si los caballos se descartan.",
    tags: ["diagnóstico", "clínica", "probabilidad", "eficiencia"],
    rel: ["occam", "hickam", "cuidados-inversos"]
  },
  {
    id: "hickam",
    nombre: "Máxima de Hickam",
    autor: "John Hickam",
    anio: "años 1950",
    cat: "med",
    enunciado: "El paciente puede tener tantas enfermedades como le venga en gana.",
    explicacion: "El contrapeso clínico a la navaja de Occam: la parsimonia diagnóstica (una sola causa que lo explique todo) es elegante, pero los pacientes reales —sobre todo mayores y crónicos— acumulan enfermedades independientes a la vez. Buscar a toda costa el diagnóstico unificador puede retrasar el tratamiento de dos problemas simples coexistentes.",
    ejemplo: "Disnea y edemas no siempre son una sola insuficiencia cardíaca: pueden ser asma más insuficiencia venosa, dos procesos banales simultáneos que ningún diagnóstico único explicaría.",
    tags: ["diagnóstico", "comorbilidad", "clínica", "parsimonia"],
    rel: ["sutton", "occam", "berkson"]
  },
  {
    id: "cuidados-inversos",
    nombre: "Ley de cuidados inversos",
    autor: "Julian Tudor Hart",
    anio: "1971",
    cat: "med",
    enunciado: "La disponibilidad de buena atención médica varía inversamente a la necesidad de la población atendida.",
    explicacion: "Quien más atención necesita (pobres, enfermos crónicos, zonas rurales) es quien menos y peor atención recibe, y la distorsión se agrava cuanto más se expone la sanidad a las fuerzas del mercado: los recursos siguen al dinero, no a la enfermedad. Formulada por un médico rural galés, es un principio rector de la salud pública y la equidad sanitaria.",
    ejemplo: "Las clínicas de élite se concentran en los barrios más sanos y ricos; los barrios con más diabetes, tabaquismo y mortalidad tienen las consultas más saturadas y los peores medios.",
    tags: ["equidad", "salud pública", "acceso", "desigualdad", "sistema sanitario"],
    rel: ["berkson", "pareto", "hierro-salarios"]
  },
  {
    id: "frank-starling",
    nombre: "Ley de Frank-Starling",
    autor: "Otto Frank y Ernest Starling",
    anio: "1895–1914",
    cat: "med",
    enunciado: "Cuanto más se llena el corazón durante la diástole, con más fuerza se contrae en la sístole (dentro de límites).",
    explicacion: "El estiramiento de las fibras cardíacas por la sangre entrante optimiza el solapamiento de sus filamentos contráctiles: el corazón bombea automáticamente lo que recibe, igualando latido a latido ambos ventrículos sin necesitar control externo. En la insuficiencia cardíaca este mecanismo se agota: más llenado deja de dar más fuerza.",
    ejemplo: "Al incorporarte de golpe o al hacer ejercicio, el retorno venoso aumenta y el corazón, sin recibir orden alguna, expulsa más sangre en cada latido: es esta ley operando en tiempo real.",
    tags: ["corazón", "fisiología", "contracción", "precarga", "cardiología"],
    rel: ["laplace-medicina", "starling-capilar", "todo-o-nada"]
  },
  {
    id: "starling-capilar",
    nombre: "Fuerzas de Starling (equilibrio capilar)",
    autor: "Ernest Starling",
    anio: "1896",
    cat: "med",
    enunciado: "El movimiento de líquido a través de los capilares resulta del balance entre presión hidrostática y presión oncótica.",
    explicacion: "La presión sanguínea empuja el líquido fuera del capilar; las proteínas del plasma (albúmina) lo succionan de vuelta. Del equilibrio entre ambas fuerzas depende que los tejidos ni se sequen ni se encharquen. Todo edema clínico se explica rompiendo este balance por uno de sus términos.",
    ejemplo: "En la desnutrición grave falta albúmina, la succión oncótica cae y el líquido queda en los tejidos: es el vientre hinchado de la hambruna. La insuficiencia cardíaca eleva la presión hidrostática y encharca piernas y pulmones.",
    tags: ["capilares", "edema", "presión", "fisiología", "albúmina"],
    rel: ["frank-starling", "fick", "poiseuille"]
  },
  {
    id: "laplace-medicina",
    nombre: "Ley de Laplace (en fisiología)",
    autor: "Pierre-Simon Laplace",
    anio: "1806",
    cat: "med",
    enunciado: "La tensión en la pared de una esfera o cilindro crece con la presión y con el radio: T = P·r.",
    explicacion: "A igual presión, una cavidad más grande soporta más tensión en su pared. Explica por qué los aneurismas crecen y revientan (más radio → más tensión → más radio: círculo vicioso), por qué el corazón dilatado trabaja peor y por qué los alvéolos pequeños necesitan surfactante para no colapsar en los grandes.",
    ejemplo: "Un globo es dificilísimo de inflar al principio (radio pequeño) y facilísimo después; un aneurisma aórtico se opera al superar cierto diámetro porque cada milímetro extra multiplica el riesgo de rotura.",
    tags: ["presión", "tensión", "aneurisma", "alvéolos", "biofísica"],
    rel: ["frank-starling", "poiseuille"],
    sim: "sim-laplace"
  },
  {
    id: "poiseuille",
    nombre: "Ley de Poiseuille",
    autor: "Jean-Léonard-Marie Poiseuille",
    anio: "1840",
    cat: "med",
    enunciado: "El flujo por un tubo crece con la cuarta potencia de su radio.",
    explicacion: "Médico y físico, Poiseuille la formuló estudiando la circulación. La cuarta potencia lo domina todo: duplicar el radio multiplica el flujo por dieciséis; estrechar un vaso un 10% recorta el flujo un tercio. Gobierna la hipertensión (las arteriolas regulan la presión con cambios mínimos de calibre), el asma y hasta la elección de catéteres.",
    ejemplo: "Por eso en urgencias una vía corta y gruesa transfunde mucho más rápido que una larga y fina, y por eso una placa que estrecha una coronaria 'solo' al 50% puede recortar el flujo drásticamente.",
    tags: ["flujo", "vasos", "radio", "hipertensión", "hemodinámica"],
    rel: ["laplace-medicina", "starling-capilar", "fick"]
  },
  {
    id: "fick",
    nombre: "Leyes de difusión de Fick",
    autor: "Adolf Fick",
    anio: "1855",
    cat: "med",
    enunciado: "La difusión de una sustancia es proporcional al gradiente de concentración y a la superficie disponible, e inversa al grosor de la barrera.",
    explicacion: "Regula cada intercambio pasivo del cuerpo: oxígeno en los alvéolos, nutrientes en la placenta, fármacos a través de membranas. Fick, además, derivó de aquí el primer método para medir el gasto cardíaco. La evolución optimiza sus tres términos: pulmones con superficie de pista de tenis y barreras de media micra.",
    ejemplo: "En el enfisema se destruye superficie alveolar y en la fibrosis se engruesa la barrera: dos maneras opuestas de estropear la misma ecuación, ambas terminan en falta de oxígeno.",
    tags: ["difusión", "gases", "membranas", "pulmón", "biofísica"],
    rel: ["poiseuille", "starling-capilar"]
  },
  {
    id: "wolff",
    nombre: "Ley de Wolff",
    autor: "Julius Wolff",
    anio: "1892",
    cat: "med",
    enunciado: "El hueso se remodela y refuerza según las cargas que soporta.",
    explicacion: "El esqueleto es un tejido vivo que se adapta: donde hay tensión mecánica se deposita hueso; donde no la hay, se reabsorbe. Las trabéculas internas del fémur siguen exactamente las líneas de fuerza, como los tirantes de un puente. Es la razón de que el ejercicio con carga prevenga la osteoporosis y la ingravidez descalcifique a los astronautas.",
    ejemplo: "El brazo dominante de un tenista profesional tiene hasta un tercio más de masa ósea que el otro; un astronauta pierde en torno al 1% de hueso por mes en órbita.",
    tags: ["hueso", "carga", "adaptación", "osteoporosis", "ejercicio"],
    rel: ["hebb", "practica"]
  },
  {
    id: "todo-o-nada",
    nombre: "Ley del todo o nada",
    autor: "Henry Pickering Bowditch",
    anio: "1871",
    cat: "med",
    enunciado: "Una fibra nerviosa o cardíaca responde con toda su fuerza o no responde en absoluto.",
    explicacion: "Si el estímulo alcanza el umbral, la célula dispara su respuesta completa; si no, nada: no existen potenciales de acción 'a medias'. La intensidad de una sensación no se codifica en el tamaño del impulso sino en su frecuencia y en cuántas fibras disparan. Es el fundamento digital del sistema nervioso.",
    ejemplo: "Apretar más fuerte una tecla de piano no envía impulsos nerviosos 'más grandes' al cerebro, sino más impulsos por segundo por más fibras a la vez.",
    tags: ["neuronas", "umbral", "potencial de acción", "corazón", "señales"],
    rel: ["frank-starling", "hebb", "weber-fechner"]
  },
  {
    id: "mendel",
    nombre: "Leyes de Mendel",
    autor: "Gregor Mendel",
    anio: "1865",
    cat: "med",
    enunciado: "La herencia se transmite en unidades discretas: uniformidad de la primera generación, segregación de los caracteres y transmisión independiente.",
    explicacion: "Cruzando guisantes en su huerto, un monje descubrió que los rasgos no se 'mezclan' como líquidos sino que se heredan como partículas (genes) que se separan y combinan con proporciones matemáticas predecibles (3:1, 9:3:3:1). Ignoradas 35 años, sus leyes son el cimiento de toda la genética, del consejo genético clínico y de la mejora agrícola.",
    ejemplo: "Dos padres de ojos marrones pueden tener un hijo de ojos claros: cada uno portaba oculta una variante recesiva que, al juntarse, se expresó, exactamente en las proporciones del huerto de Mendel.",
    tags: ["genética", "herencia", "genes", "recesivo", "dominante"],
    rel: ["stigler", "todo-o-nada"]
  },
  {
    id: "courvoisier",
    nombre: "Ley de Courvoisier",
    autor: "Ludwig Courvoisier",
    anio: "1890",
    cat: "med",
    enunciado: "Ictericia con vesícula palpable e indolora: la causa probablemente no son cálculos, sino una obstrucción tumoral.",
    explicacion: "Los cálculos biliares inflaman crónicamente la vesícula y la vuelven fibrosa e incapaz de dilatarse; una vesícula grande, tensa y sin dolor sugiere que algo distinto —típicamente un tumor de páncreas— obstruye el colédoco de forma gradual. Es un ejemplo clásico de cómo un signo físico sencillo ordena un diagnóstico grave.",
    ejemplo: "Paciente con piel amarilla y una masa lisa e indolora bajo las costillas derechas: el clínico prioriza descartar cáncer de cabeza de páncreas antes que una simple colelitiasis.",
    tags: ["ictericia", "vesícula", "diagnóstico", "semiología", "páncreas"],
    rel: ["sutton", "hickam"]
  },
  {
    id: "hy",
    nombre: "Ley de Hy",
    autor: "Hyman Zimmerman",
    anio: "1978",
    cat: "med",
    enunciado: "Un fármaco que causa daño hepático con ictericia provoca mortalidad grave en al menos uno de cada diez casos.",
    explicacion: "Zimmerman observó que cuando un medicamento produce lesión hepatocelular suficiente para causar ictericia (sin obstrucción), el hígado ha perdido gran parte de su reserva funcional y el pronóstico es sombrío. La FDA la usa como criterio centinela: dos 'casos de Hy' en un ensayo clínico pueden tumbar el desarrollo de un fármaco.",
    ejemplo: "En un ensayo, dos pacientes desarrollan transaminasas altas más bilirrubina elevada sin otra causa: el comité de seguridad detiene el estudio, porque la ley de Hy predice muertes si el fármaco llega a millones de personas.",
    tags: ["hígado", "fármacos", "toxicidad", "ictericia", "farmacovigilancia", "psiquiatría"],
    rel: ["courvoisier", "twyman"]
  },
  {
    id: "kraepelin",
    nombre: "Dicotomía de Kraepelin",
    autor: "Emil Kraepelin",
    anio: "1899",
    cat: "med",
    enunciado: "Las psicosis mayores se dividen en dos grandes entidades: la demencia precoz (esquizofrenia) y la enfermedad maníaco-depresiva (trastorno bipolar).",
    explicacion: "No es una 'ley' natural sino el principio clasificatorio que fundó la psiquiatría moderna: distinguir las psicosis por su curso y desenlace, no solo por sus síntomas del momento. Los manuales diagnósticos actuales (DSM, CIE) descienden de esta dicotomía, hoy discutida por la genética, que encuentra un continuo entre ambos polos más que una frontera.",
    ejemplo: "Dos pacientes con delirios idénticos hoy: si el curso es deteriorante y continuo se orienta como esquizofrenia; si es episódico con recuperación entre fases, como trastorno bipolar. El tratamiento y pronóstico cambian por completo.",
    tags: ["psiquiatría", "esquizofrenia", "bipolar", "diagnóstico", "clasificación"],
    rel: ["kandel", "hickam"]
  },
  {
    id: "kandel",
    nombre: "Principio de Kandel",
    autor: "Eric Kandel",
    anio: "1998",
    cat: "med",
    enunciado: "Todo proceso mental es un proceso cerebral, y toda psicoterapia eficaz produce cambios físicos en el cerebro.",
    explicacion: "El Nobel de Medicina 2000 formuló los principios que unifican psiquiatría y neurociencia: aprender remodela sinapsis (lo demostró en el caracol Aplysia), luego la palabra que cura también esculpe circuitos. Disolvió el falso dilema 'biológico o psicológico': los fármacos y la conversación terapéutica operan, por vías distintas, sobre el mismo órgano.",
    ejemplo: "Estudios de neuroimagen muestran que la terapia cognitivo-conductual para la fobia o el trastorno obsesivo normaliza la actividad de los mismos circuitos que modifican los fármacos.",
    tags: ["psiquiatría", "neurociencia", "psicoterapia", "plasticidad", "mente"],
    rel: ["hebb", "kraepelin", "ebbinghaus"]
  }
];
